Feature/unity/util/json manager
GreenTeaProgrammers/TasQuest pull request #8
Opened 2023-09-06 04:53 UTC by KikyoNanakusa

# JsonManager.csを作成しました。
JsonManagerはLoadJsonとSaveJsonの2つの関数を持ちます。
LoadJsonはJSONファイルを読み込み、JsonData型のインスタンスを返します。
SaveJsonはJsonData型のインスタンスを引数として受け取り、JSONファイルとして保存します。

## 既知の問題
### JsonData Class
Jsonの内容を扱うためにJsonDataクラスを作成しましたが、命名に問題があると思っています。
なにかいい命名ないでしょうか。
### Jsonのパス
Jsonファイルが今のところどこに保存されるのか不明なのでダミーのJsonファイルを用意してそのパスにアクセスするようになています。これは、Swiftとマージする際に解決すると思います。

## JsonManagerの機能について
何か他に実装したほうが良い機能が思いつく方いたら提案してください

2023-09-06 05:02 UTC, KinjiKawaguchi requested changes

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +public class JsonData
```suggestion
public class AppData
```
アプリに関するデータということで、ルートはAppDataでどうでしょうか

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +    public string createdAt;
```suggestion
    public string createdAt;　// YYYY-MM-DD/HH:MM:SS
```
といった具合でデータの不定な日時表現を表した方が保守性は上がりそうです。

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +    public string updatedAt;
同上

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +    public string dueDate;
同上こちらも時間持たせる感じでお願いします。

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +    private const string JSON_PATH = "Assets/Resources/DummyJson.json";
このPathを決めてからMergeしましょうか

2023-09-06 05:02 UTC, KinjiKawaguchi commented on Unity/Assets/Scripts/json/JsonManager.cs
> +        catch (Exception e)
エラーハンドリングはViewにも反映させる必要がありそうです。

2023-09-06 05:24 UTC, KikyoNanakusa commented
TaskクラスにdueDateがなかったので追加しました。
クラス名をAppDataに変更しました。
エラーが発生した際にその旨を表示するUIを呼び出す関数を作成しました。
UI自体は未着手なので関数の中身は空です

2023-09-07 07:16 UTC, KinjiKawaguchi commented
ダミーファイルのパス云々はどうしますか？

2023-09-07 07:18 UTC, KikyoNanakusa commented
その辺いろいろ書き換えてからもう一回コミットします

2023-09-07 07:41 UTC, KikyoNanakusa commented
パス関連はまだ使用が未定なので引数で指定できるようにしときました。

2023-09-07 07:52 UTC, KinjiKawaguchi commented
LGTM マージします。

2023-09-07 07:53 UTC, KinjiKawaguchi approved these changes

2023-09-07 07:54 UTC, merged